### ISSUE TITLE
Add colors to "Folders" sidebar reflecting Git status

### ISSUE THREAD

**Issue by astronaute77** [kemayo/sublime-text-git#204]
I'm not sure if Sublime text 2 is flexible enough to add this feature but I suggest it in case it is:

EGit for Eclipse allows the git status to be displayed directly on folders and files as colored icons, it would be great to have something similar in Sublime Text 2 as it is not easy to work in large projects without it even with this great plugin.
For this reason I develop mainly in Eclipse even if I really love ST2...

http://imageshack.us/a/img121/3263/yk6d.png

Please tell me what you think about this feature and if it is possible to implement.

Thank you

**Comment by math-u** [comment]
+1

**Comment by ticklemynausea** [comment]
+1

**Comment by johnnyghost** [comment]
+1

**Comment by imran-aspire** [comment]
+1 , really need this in ST3

**Comment by kemayo** [comment]
I will _absolutely_ unlock this and implement the feature, if Sublime ever acquires the APIs required to do so. Until then, I'd recommend requesting the enhanced APIs for it on http://sublimetext.userecho.com

**Comment by kemayo** [comment]
There's also a recent API-wants thread on the ST forums -- if you want to go and upvote the relevant suggestion there, that might help. https://forum.sublimetext.com/t/api-suggestions/20640/26
