### ISSUE TITLE
Git command cannot be found

### ISSUE THREAD

**Issue by foxbunny** [kemayo/sublime-text-git#212]
This started happening all of a sudden without making any changes to OS, git, nor ST2 itself. The exact message is:

```
error: Git binary could not be found in PATH

Consider using the git_command setting for the Git plugin

PATH is: /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/core_perl:$HOME/bin
```

Git is located at /usr/bin/git. I've added user setting for `git_command` like so:

```
{
    "git_command": "/usr/bin/git"
}
```

but that doesn't help at all.

EDIT: I'm on Arch Linux x86_64, using SublimeText2 2.0.1 build 2217, and Git is 1.8.0.

**Comment by 312024196** [comment]
@davidagee Thanks! It works for me!
