### ISSUE TITLE
Add / commit selected hunk does nothing

### ISSUE THREAD

**Issue by phobia** [kemayo/sublime-text-git#221]
When running Add / commit selected hunk I only get a message in the console saying "nothing to commit", allthough uncommited lines are currently selected.

**Comment by alimuldal** [comment]
Likewise (using ST3)

**Comment by odyniec** [comment]
I started having the same issue when I switched from Ubuntu to Arch (ST 2.0.2). I found out that "Add selected hunk" seems to work if it's done right after the file is saved.
