### ISSUE TITLE
fatal: unable to auto-detect email address

### ISSUE THREAD

**Issue by rarutu** [kemayo/sublime-text-git#246]
Can anyone tell me how to fix this ... i do not know where to put my email and name ... although git was on my computer before installing sublime text 2

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'me@me-PC.(none)')

**Comment by Sammy-iiitb** [comment]
Git is not able to recognize your email or user name probably
don't change user with your name only change you with your email id.

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

Hope this works!!!

**Comment by shankarimoorthy** [comment]
thanks this is working

**Comment by YohanesDoank** [comment]
thx sir Sammy its working

**Comment by paaguti** [comment]
FreeBSD 10.1, tried remedy but it is not working for me

**Comment by shifatmbstu** [comment]
Open terminal and paste it 
git config --global user.email "you@example.com"
hit enter 
git config --global user.name "Your Name"
hit enter

It worked for me ...

**Comment by Akshay-NIIT** [comment]
thanks it works

**Comment by victormolinaasencios** [comment]
gracias  shifatmbstu

**Comment by aashutoshtaikar** [comment]
its pretty simple but tricky at the first time. 
For example:
If my email is mrsuicidesheep@gmail.com
type: 
git config --global user.email mrsuicidesheep@gmail.com 
OR 
If my username is mrsuicidesheep
type:
git config user.name mrsuicidesheep

**Comment by MazharIITK** [comment]
To get rid of that , just open another terminal and run the following:
1) git config --global user.email "you@example.com"
then,
2) git config --global user.name "Your Name"
Means, you just have to copy that and press enter one by one.
Hope it helped.

**Comment by dmathisen** [comment]
I have user.name and user.email defined (and they match my github account), but I still get this error. Screenshot attached. Anyone have any idea why?

![1](https://user-images.githubusercontent.com/684701/27797581-36549bfa-5fdc-11e7-9904-11260f3fb429.PNG)

**Comment by cjwijtmans** [comment]
this is frustrating it is supposed to be defined, i check both global and local repo but i still get this error.

**Comment by jajhonrod1620** [comment]
I got an alternate solution from here:

[https://stackoverflow.com/questions/16433970/unable-to-auto-detect-email-address?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](url)

Basically it's edit de config file in our git directory.

Local/repo/location/.git/
open "config" file there, and set your parameters like the example (add to the end of the file):

[user]
    name = YOUR-NAME
    email = YOUR-EMAIL-ADDRESS

Hope it helps.

**Comment by pavansaikiran** [comment]
Thank you ,this worked for me also😁

**Comment by hmahajan99** [comment]
> I got an alternate solution from here:
> 
> [https://stackoverflow.com/questions/16433970/unable-to-auto-detect-email-address?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](url)
> 
> Basically it's edit de config file in our git directory.
> 
> Local/repo/location/.git/
> open "config" file there, and set your parameters like the example (add to the end of the file):
> 
> [user]
> name = YOUR-NAME
> email = YOUR-EMAIL-ADDRESS
> 
> Hope it helps.

This worked for me!

**Comment by MrEmperawr** [comment]
> To get rid of that , just open another terminal and run the following:
> 
> 1. git config --global user.email "[you@example.com](mailto:you@example.com)"
>    then,
> 2. git config --global user.name "Your Name"
>    Means, you just have to copy that and press enter one by one.
>    Hope it helped.

This worked for me! Thanks a bunch MazharIITK

**Comment by rakesh415** [comment]
Thank you Sammy-iiitb . It's fixed my issue

**Comment by jesusmariabermudez** [comment]
acabo de solucionar este mismo problema, investigando un poco logre solucionarlo..

se debe escribir los comando fuera de la carpeta donde hemos estado ejecutando los comando de git status o git add.. solo salimos a la carpeta local y ejecutamos y listo.

**Comment by erix2016** [comment]
Hice lo que dijiste, pero tampoco me resultó.

**Comment by Margotte83** [comment]
THX !!! 🙏

**Comment by Joe294ME** [comment]
> Open terminal and paste it
> git config --global user.email "[you@example.com](mailto:you@example.com)"
> hit enter
> git config --global user.name "Your Name"
> hit enter
> 
> It worked for me ...

"LIFE_SAVER" bruh

**Comment by Al95-diallo** [comment]
Merci beaucoup. Cela a résolu mon problème!!!

**Comment by Rierii** [comment]
> I have **user.name** and **user.email** defined (and they match my github account), but I still get this error. Anyone have any idea why?
> 
> **EDIT:** when running `git config --local -l`, I didn't see any user.email or user.name. I'm not sure why. Fix was to run `git config user.email "me@domain.com"` and `git config user.name "me"` (**without --global**)

Bruuh. U sure a life safer. this one work for me, thanks

**Comment by naveedum** [comment]
omitting "--global" worked for me. As shown below ...

git config user.email abc@xyz.com
git config user.name myusername

**Comment by Vishnu-Tej** [comment]
> Git is not able to recognize your email or user name probably
> don't change user with your name only change you with your email id.
> 
> git config --global user.email "[you@example.com](mailto:you@example.com)"
> git config --global user.name "Your Name"
> 
> Hope this works!!!

#thanks so much it worked

**Comment by Vishnu-Tej** [comment]
thanks it worked

**Comment by itsmesangram5** [comment]
> > I got an alternate solution from here:
> > [https://stackoverflow.com/questions/16433970/unable-to-auto-detect-email-address?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](url)
> > Basically it's edit de config file in our git directory.
> > Local/repo/location/.git/
> > open "config" file there, and set your parameters like the example (add to the end of the file):
> > [user]
> > name = YOUR-NAME
> > email = YOUR-EMAIL-ADDRESS
> > Hope it helps.
> 
> This worked for me!

Thanks ......This  Work for me

**Comment by Prafulla-Santosh-Dethe** [comment]
> Open terminal and paste it git config --global user.email "[you@example.com](mailto:you@example.com)" hit enter git config --global user.name "Your Name" hit enter
> 
> It worked for me ...Thanks:)

**Comment by Bigben202** [comment]
please what if I make mistake in addind the user name and email how can I resolve that ??

**Comment by cheshir789** [comment]
> 

Thanks. It realy worked!

**Comment by TimoneldelSur** [comment]
En mi caso lo solucione agregando **mailto:**

git config --global user.mail       mailto:tumail@tudominio.xxx

es lo mismo que copiar y pegar alguna de las respuestas donde figura el mail en color celeste (mailto:xxxxx)

Espero sirva. Saludos!!

**Comment by victorjohnson-usda** [comment]
> a



> To get rid of that , just open another terminal and run the following:
> 
>     1. git config --global user.email "[you@example.com](mailto:you@example.com)"
>        then,
> 
>     2. git config --global user.name "Your Name"
>        Means, you just have to copy that and press enter one by one.
>        Hope it helped.
this didn't work

**Comment by Awitie11** [comment]
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'ec2-user@development-server.(none)')
