### ISSUE TITLE
Add option to ignore whitespace in git blame

### ISSUE THREAD

**Issue by dpashkevich** [kemayo/sublime-text-git#363]
It's very helpful to ignore whitespace-only changes when doing `git blame`. The command line key for this is `git blame -w`.

**Comment by ipetropolsky** [comment]
+1

**Comment by jnu** [comment]
adding `?w=1` to the url works for diffs, would like to see this for blame as well

**Comment by vhermecz** [comment]
+1

**Comment by jmecosta** [comment]
+1

**Comment by Emanuele-Spatola** [comment]
+1

**Comment by LeEnno** [comment]
As far as I can see this is implemented in https://github.com/kemayo/sublime-text-git/blob/517f7b49c31af0caab68f439f0e02be54e0f8be0/history.py#L15 and can be closed

**Comment by kemayo** [comment]
Arguably, the issue is for "add an option to..." but, y'know, it's close.
