### ISSUE TITLE
"git show" on a commit hash?

### ISSUE THREAD

**Issue by garyking** [kemayo/sublime-text-git#364]
Let's say I've got a commit hash from this Git package, such as after running "git blame" on a line.

How can I use "git show" on that commit in this package? At the moment I'm just running "Git: Custom command". Is there a better way of doing this?

Filtering the "git log all" with a commit hash doesn't seem to work; it only seems to filter based on the commit message.

**Comment by evheny0** [comment]
It's also can be handy, if there would be an ability to double click on commit hash and get a commit body in a new tab

**Comment by langtianlang** [comment]
+1

**Comment by kemayo** [comment]
There actually is an ability to jump to a hash from a blame view -- if you press enter while you're on the hash, it does so.

**Comment by langtianlang** [comment]
that works only in blame (and only in insert mode in vintage). would love to just have a `git show` command.

**Comment by kemayo** [comment]
cf56cde
