### ISSUE TITLE
Cannot commit

### ISSUE THREAD

**Issue by evenfrost** [kemayo/sublime-text-git#371]
Every time I try to do git commit, I get this error: "fatal: Unable to create '/home/evenfrost/work/projects/aword/.git/index.lock': File exists.". There is no such file though. I believe this is somehow related to the fact that I've upgraded git to 2.1.0, cause guys from SO had similar problems with the plugin and newer versions of git.

**Comment by alextegelid** [comment]
I can confirm that the problem I experienced only occurred on a large repo aswell. All other repos were/are still working fine

—
Alexander Tegelid
070-508 49 90
alex@tegelid.se
—

**Comment by ceronman** [comment]
I confirm this problem. Adding files works but commit and checkout commands fail with this error.

**Comment by kemayo** [comment]
Good debugging, @jotson. I can work around that.

**Comment by kemayo** [comment]
Okay, I think 9d28846 should stop it happening. Any command that detects an index.lock will try to wait until it goes away.

**Comment by jotson** [comment]
Thanks, @kemayo. Seems to be working. Confirmed that I saw the "waiting for index.lock..." message in the SublimeText console.

**Comment by DenisBY** [comment]
got this error:
```
waiting for index.lock ['git', 'push']
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 524, in run_
    return self.run(**args)
  File "git in /home/denis/.config/sublime-text-3/Installed Packages/Git.sublime-package", line 433, in run
  File "git in /home/denis/.config/sublime-text-3/Installed Packages/Git.sublime-package", line 231, in run_command
TypeError: do_when() got multiple values for argument 'callback'
```

**Comment by beet** [comment]
I managed to trigger this error today by inadvertently quitting ST with the commit message composition tab open. Meant to delete the message and close the tab to abort the commit, but hit COMMAND+Q by mistake.

The `index.lock` file definitely doesn't exist, but cannot checkout or presumably commit files, but log, diff, etc work.
