### ISSUE TITLE
Yet another ST3

### ISSUE THREAD

**Issue by radaniba** [kemayo/sublime-text-git#381]
Before asking my question I went through all the comment of people using this plugin and having the same issue than mine. In my opinion, (no offence @kemayo ) the plugin is definitely not ready for ST3 or need some improvements, all the comment I saw for people complaining about this issue are vague and not really helpful (this is a honest review by a user do not take it bad)

Now that I ruined all my chances to have a reply from you or anyone :) here is the bug I am having in the console 

```
Traceback (most recent call last):
  File "/Users/raniba/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/commands/remove_package_command.py", line 76, in unignore_package
    self.reenable_package(self.package, 'remove')
  File "/Users/raniba/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_disabler.py", line 145, in reenable_package
    events.clear('remove', package)
  File "/Users/raniba/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/events.py", line 69, in clear
    do_clear()
  File "/Users/raniba/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/events.py", line 64, in do_clear
    del _tracker[type][package]
KeyError: 'Git'
```

I tried  : 

- Installing via git clone and checkout to python3 branch
- Install through package manager
- removed updated etc ... 

None of the options works, the menu still doesnt show up, the files are installed but not operational.

In my opinion there is no enough informative log file to spot the problem correctly, so if you can work on this that would be great, in order to once and for all try to identify the problem 

Cheers

Thanks

**Comment by radaniba** [comment]
*Update on this : my solution*

I installed a fresh version of ST igniring all my packages and went through the diff file by file for all the preferences files and found out that in my old install Git was added in the ignored_packages in `Sublime Text 3/Packages/User/Preferences.sublime-settings`

So I went back to my Sublime where I had the problem, removed Git from the ignored packages, uninstalled using package manager, reinstalled using package manager, and voila ! it worked again

Hope that helps someone else

Cheers

**Comment by kemayo** [comment]
That does sound strange. I don't know if there's anything that would have automatically done that -- certainly nothing that's directly part of this plugin -- perhaps you disabled it at some point to try out another package, and forgot about it?

**Comment by radaniba** [comment]
No that's not possible, I use Git everyday and just cannot disable it on ST, that said, it can be a conflict with another plugin but there is no way of knowing that unless I reinstall all my plugins one by one but this will take forever :)
