### ISSUE TITLE
Can't commit in latest version

### ISSUE THREAD

**Issue by nietonfir** [kemayo/sublime-text-git#383]
With the change introduced in https://github.com/kemayo/sublime-text-git/commit/712d7de6c40dfdaf00bc38a58227a9a71c1d53aa one can't commit from within ST2 (2.0.2 build 2221) with the following error message:
```python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 180, in on_close
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 179, in <lambda>
  File "./commit.py", line 153, in on_close
  File "./commit.py", line 124, in message_done
TypeError: 'encoding' is an invalid keyword argument for this function
```
Python version in use is
```bash
$ python --version
Python 2.7.5
```
and according to the [documention](https://docs.python.org/2/library/functions.html#open) the keyword argument is for [Python 3](https://docs.python.org/3/library/functions.html#open) only.

**Comment by ballyhoos** [comment]
I have the same error. Cannot 'commit', however a 'quick commit' works.

Git package version "2015.01.15.14.49.08".  (No idea of the build number)
Python 2.6.1
OSX 10.6

**Comment by nietonfir** [comment]
@kemayo thx, but you reintroduced that flag in https://github.com/kemayo/sublime-text-git/commit/aa1b104a501688a70472cf678aa7f36af396c1e1
Maybe you should detect the python version or something e.g. `sys.version_info > (3, 0)`. See http://sweetme.at/2013/10/21/how-to-detect-python-2-vs-3-in-your-python-script/

**Comment by kemayo** [comment]
@nietonfir: it's a completely different call to a different library. It should work as-is in anything greater than python 2.4 according to https://docs.python.org/2/library/codecs.html

**Comment by nietonfir** [comment]
@kemayo I see, my bad. It's gone now, so maybe the plugin wasn't updated properly and I can't see anything in the logs now. Thx. ;-)

**Comment by Azakur4** [comment]
@kemayo can u put this fix for sublime text 3 too please.
