### ISSUE TITLE
Error Adding File :: Git/index.lock exists

### ISSUE THREAD

**Issue by daveyand** [kemayo/sublime-text-git#406]
95% of the time when i'm doing a quick commit within sublime i get the an error saying: 

"Error Adding File: 
fatal: Unable to create '/paht/to/repo/.git/index.lock" file exists
if no other git process is currently runnint, this probably means a git process crashed in this repository earlier .... 

If i run "quick commit" after i get this error the commit works as expected. I dont know why this keeps happening, any ideas?

**Comment by j-crowe** [comment]
I just noticed this happening as well.
Normal commits work fine, just quick commit.

**Comment by gBopHuk** [comment]
I dpn't understand how to use Normal commit. Please Example!
