### ISSUE TITLE
'git' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by olemarius** [kemayo/sublime-text-git#41]
I'm guessing this has something to do with:

"git_command: a path to your git binary if it's not in the $PATH available to Python (you'll get an error message if you need to set this)", so I tried to followed the comment in git.sublime-settings

```
// if present, use this command instead of plain "git"
// e.g. "/Users/kemayo/bin/git" or "C:\bin\git.exe"
```

I use Windows 7, and as far as I know the git binary is located at 

C:\Program Files (x86)\Git\bin\git.exe

I also followed your wiki to the point where I copy the Git.sublime-settings from the Git folder to the User folder, but seems neither "C:\bin\git.exe", or  in my case "C:\Program Files (x86)\Git\bin\git.exe" gives a invalid escape error. I tried JSON escaping with \ but still get the same error when testing git commands:

'git' is not recognized as an internal or external command, operable program or batch file.

Any ideas what I'm missing?

**Comment by abhilashlohar** [comment]
Error:-
git: 'Files' is not a git command. See 'git --help'.

Did you mean this?
	ls-files

**Comment by abhilashlohar** [comment]
"C:\Program Files\Git\bin\git.exe"
