### ISSUE TITLE
Git Add... won't add a folder

### ISSUE THREAD

**Issue by nikmartin** [kemayo/sublime-text-git#410]
If I bring up Tools > Git > Whole Repo > Add... and select a folder to add, the command just returns without adding anything.  On SOME folders I select, but not all, I see this in the Console:
```
waiting for index.lock ['git', 'rm', '--', 'models/schemas/pcr/eCustomResults/']
waiting for index.lock ['git', 'rm', '--', 'models/schemas/pcr/eDevice/']
waiting for index.lock ['git', 'rm', '--', 'models/schemas/pcr/eCustomResults/']
```
This output isn't connected to the folder's current status in git, but it happens maybe every 2 folders I TRY to add, but none get added, console output or not.

I'm using ST3 on Linux, 64 Bit Debian

**Comment by kleinfreund** [comment]
I am not able to add folders via `Add...` as well. It works when I try to add files with the option to add all files. I am on Windows 8 and use Sublime Text 3.

**Comment by bordaigorl** [comment]
This was happening even before the "lock waiting" mechanism was introduced.
Any update?

**Comment by g105b** [comment]
I've just installed this package and am experiencing this issue. Is there an ETA for when it will be supplied as a fix? For now I'll checkout manually.
