### ISSUE TITLE
How to close the bottom window opened after a push

### ISSUE THREAD

**Issue by PedroVinicius** [kemayo/sublime-text-git#415]
When I make a push or pull, a window is opened at bottom of the editor, showing the git command output. How to hide this? Has some hotkey or a menu option in the toolbar? 

Thanks.

**Comment by kleinfreund** [comment]
You can hide the build panel by pressing `Esc` or have it not show up on build by setting the following option in your user preferences:

```json
"show_panel_on_build": false,
```

I remember there was a package that would hide the panel on successful builds only, but I can't find it right now.

**Comment by PedroVinicius** [comment]
This work for me! Thanks! :+1:
