### ISSUE TITLE
Do not word wrap on git blame

### ISSUE THREAD

**Issue by Jonnymcc** [kemayo/sublime-text-git#422]
When I do git blame word wrap is always on by default and I always turn it off because when many lines are wrapping the output of blame looks messy. Can we disable word wrap when using git blame?

**Comment by brendanator** [comment]
Add this to the Git Blame syntax specific settings
```json
{
    "word_wrap": false
}
```

**Comment by Jonnymcc** [comment]
Is there a scratch view that is created where word wrap should be enabled? Most of the git command output is all pre-formatted right?

**Comment by sjuchno** [comment]
@brendanator how can I add it to "the Git Blame syntax specific settings"
I've added your code to Package Settings > Git > Settings - User but it does not work.

**Comment by brendanator** [comment]
@sjuchno 
First open Git Blame on a file, then find the menu item: Preferences > Settings - More > Syntax Specific. This will be the Git Blame syntax settings file

**Comment by sjuchno** [comment]
@brendanator Thank you!

**Comment by Jonnymcc** [comment]
The pull request I originally made was merged.
