### ISSUE TITLE
compatibility with sublime text 3

### ISSUE THREAD

**Issue by michahell** [kemayo/sublime-text-git#435]
It is very unclear wether or not this plugin supports sublime text 3. Only by searching through issues it becomes clear, it might be good to add 'support for sublime text 3' or something to the read me or at least wiki?

**Comment by goforgold** [comment]
Hey @michahell 

Have you tried it with `3` ? Does it work fine with Sublime Text 3 ?

**Comment by kemayo** [comment]
It's compatible with 3. Package Control being the assumed method of installation, just works.

**Comment by michahell** [comment]
@kemayo Okay, thanks. The tip still stands though, as also your answer is still inside an issue ;)
