### ISSUE TITLE
Interference with Arcanist

### ISSUE THREAD

**Issue by drew-gross** [kemayo/sublime-text-git#444]
This plugin interacts poorly with Arcanist, because it creates index.lock files at the same times as arc is trying to run git commands.

To repoduce:

1. Install Arcanist and this plugin.
2. Set "subl -w" as your editor.
3. Run arc diff in a repository that has changes.
4. arc command will often fail due the existence of an index.lock file.

I'm happy to help solve this issue if you would like help.

**Comment by timlegrand** [comment]
The creation of such `index.lock` files appears each time I get the focus on the SublimeText window (on Linux, with either Alt+Tab or mouse click).

This may disturb any other git-related tool (e.g. [giterm](https://testpypi.python.org/pypi/giterm/)).

The plug-in should definitely not create such files when not action was requested (only window focus). What is this Git action being performed?

**Comment by kemayo** [comment]
It's the check for the statusbar display, so yes, a `git status`.

I should say that I've been using arcanist for ages with `subl -w`, and haven't had this issue occur, so there's presumably something slightly fiddly about making it happen.

**Comment by drew-gross** [comment]
Is there a setting to disable the status bar info? I primarily use this plugin through cmd+shift+p anyway. Happy to contribute code to implement that setting if it doesn't exist.

I use a forked arcanist, which could be causing the issue, or it may be an issue elsewhere in my alias.

**Comment by kemayo** [comment]
Yeah, if you check out [the Git package settings](https://github.com/kemayo/sublime-text-git/blob/master/Git.sublime-settings), you'll find `statusbar_branch` and `statusbar_status`. If you set them both to `false` it'll completely avoid running commands during times of focus / buffer-saving.

**Comment by drew-gross** [comment]
Thanks, that resolved the problem with arc.

**Comment by timlegrand** [comment]
Personnally this issue was conflicting with giterm, so I made giterm stop tracking for `.git` and `.git/index.lock` entries, and no more issue :)

Anyway, the fact that Git writes files for a read-only action `git status` is a well-known non-sense. A walkaround is to make Git run as *a read-only user*. Read-only actions then performs properly *without any file write*.
