### ISSUE TITLE
installed failed

### ISSUE THREAD

**Issue by ckrad** [kemayo/sublime-text-git#447]
i used package manager to install. but the file is not lastest. so i git clone the project. and put it to packages fold. but it not work.

**Comment by ckrad** [comment]
i changed the sublime-package file to zip file. and update the code to lastest (because chinese char problem). then chaged it to sublime-package file. but it still not work

**Comment by kemayo** [comment]
I'd hypothesize that you might be placing things in the wrong folder. Check out http://sublimetext.info/docs/en/extensibility/packages.html for more details, there.
