### ISSUE TITLE
Custom diff commands

### ISSUE THREAD

**Issue by whophil** [kemayo/sublime-text-git#449]
I'm interested in using a custom diff command and having the output returned to a Sublime Text tab. In particular, I'd like to use `git diff --color-words`. Is this possible now? If not, would it be possible to make the choice of `diff` command a user-configurable setting?

**Comment by Silberling** [comment]
+1, I would like to skip spaces because I have files which have different line endings, indentation changed, etc which distords the diff.

**Comment by whophil** [comment]
This is closely related enough to be a dupe of https://github.com/kemayo/sublime-text-git/issues/146

**Comment by whophil** [comment]
Closed by https://github.com/kemayo/sublime-text-git/pull/574
