### ISSUE TITLE
Unable to Use All of the Sudden (UnicodeDecodeError)

### ISSUE THREAD

**Issue by DerekFoulk** [kemayo/sublime-text-git#452]
Sublime Text Git was working fine for me. Now, I am unable to use any part of this extension with any project/repo. I think I am going to die lol. I really depend on this extension. Any idea what is causing the errors (seen below in my console)?

    DPI scale: 1
    startup, version: 3083 windows x64 channel: stable
    executable: /C/Program Files/Sublime Text 3/sublime_text.exe
    working dir: /C/Program Files/Sublime Text 3
    packages path: /C/Users/Owner/AppData/Roaming/Sublime Text 3/Packages
    state path: /C/Users/Owner/AppData/Roaming/Sublime Text 3/Local
    zip path: /C/Program Files/Sublime Text 3/Packages
    zip path: /C/Users/Owner/AppData/Roaming/Sublime Text 3/Installed Packages
    ignored_packages: ["Vintage"]
    pre session restore time: 0.119738
    startup time: 0.162738
    first paint time: 0.163738
    reloading plugin Default.block
    reloading plugin Default.comment
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_context_url
    reloading plugin Default.open_file_settings
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.quick_panel
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin CSS.css_completions
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin 0_package_control_loader.02-bz2
    reloading plugin GitGutter-Edge.git_gutter
    reloading plugin GitGutter-Edge.git_gutter_change
    reloading plugin GitGutter-Edge.git_gutter_compare
    reloading plugin GitGutter-Edge.git_gutter_events
    reloading plugin GitGutter-Edge.git_gutter_handler
    reloading plugin GitGutter-Edge.git_helper
    reloading plugin GitGutter-Edge.view_collection
    reloading plugin HTML5.encode_html_entities
    reloading plugin HTML5.html_completions
    reloading plugin LESS.less_completions
    reloading plugin Package Control.1_reloader
    reloading plugin Package Control.2_bootstrap
    reloading plugin Package Control.Package Control
    reloading plugin PackageResourceViewer.package_resource_viewer
    reloading plugin PackageResourceViewer.package_resources
    reloading plugin SideBarEnhancements.SideBar
    reloading plugin SideBarEnhancements.SideBarAPI
    reloading plugin SideBarEnhancements.SideBarDefaultDisable
    reloading plugin Sublimerge Pro.Sublimerge
    reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
    reloading plugin Terminal.Terminal
    plugins loaded
    Package Control: Skipping automatic upgrade, last run at 2016-01-08 16:00:12, next run at 2016-01-08 17:00:12 or after
    ignored packages updated to: ["Git", "Vintage"]
    reloading Packages/User/Package Control.sublime-settings
    reloading Packages/User/Preferences.sublime-settings
    reloading Packages/User/Package Control.sublime-settings
    ignored packages updated to: ["Vintage"]
    reloading plugin Git.add
    reloading plugin Git.annotate
    reloading plugin Git.commit
    reloading plugin Git.diff
    reloading plugin Git.flow
    reloading plugin Git.git
    reloading plugin Git.history
    reloading plugin Git.repo
    reloading plugin Git.stash
    reloading plugin Git.status
    reloading plugin Git.statusbar
    generating syntax summary
    generating meta info summary
    reloading Packages/User/Package Control.sublime-settings
    reloading Packages/User/Preferences.sublime-settings
    reloading Packages/User/Preferences.sublime-settings
    Exception in thread Thread-17:
    Traceback (most recent call last):
      File "git in C:\Users\Owner\AppData\Roaming\Sublime Text 3\Installed Packages\Git.sublime-package", line 93, in _make_text_safeish
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 6124073: invalid continuation byte

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "./threading.py", line 901, in _bootstrap_inner
      File "git in C:\Users\Owner\AppData\Roaming\Sublime Text 3\Installed Packages\Git.sublime-package", line 194, in run
      File "git in C:\Users\Owner\AppData\Roaming\Sublime Text 3\Installed Packages\Git.sublime-package", line 95, in _make_text_safeish
      File "./encodings/cp1252.py", line 15, in decode
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3935560: character maps to <undefined>

    Traceback (most recent call last):
      File "commit in C:\Users\Owner\AppData\Roaming\Sublime Text 3\Installed Packages\Git.sublime-package", line 101, in diff_done
    TypeError: sequence item 6: expected str instance, bytes found

**Comment by kemayo** [comment]
Could you try updating the plugin and restarting Sublime? Recent changes rearranged some files into submodules, and this bit

```reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar```

...implies that you're still on the old paradigm. Or mixed up, which could be confusing it.

**Comment by kemayo** [comment]
...actually, perhaps not. Package Control hasn't merged in the pull request to update to that version yet, so that'd presumably not be it.

**Comment by DerekFoulk** [comment]
One important note I suppose would be that the repo that is having issues contains WordPress. With the different language files, I assume there are more than a few non-UTF-8 characters in those files... Think this could be the issue?

**Comment by isaac-ramthal-css** [comment]
I second this.  The plugin is not working in any way for me now.  Git blame or even git log current file is not working.

**Comment by kemayo** [comment]
@DerekFoulk Do you still experience this, since the refactored version has landed into package control since I last commented?

**Comment by isaac-ramthal-css** [comment]
@DerekFoulk  It is working now but it gives me an error when i try to run Git Blame from the command pallette saying something like **'GIT Blame tm language not found'**.  Rest the plugin seems to work now. Thanks.

**Comment by DerekFoulk** [comment]
Sorry I have been neglecting my notifications due to an increase in projects. I am able to use the plugin 100% at the moment. Thanks a ton!
