### ISSUE TITLE
Can't commit anything since latest update a few days ago.

### ISSUE THREAD

**Issue by GaryKing** [kemayo/sublime-text-git#454]
When I go to commit, "COMMIT_EDITMSG" opens up as expected, but it has no syntax highlighting anymore, and I get the following error:

`Error loading syntax file "Packages/Installed Packages/syntax/Git Commit Message.tmLanguage": Unable to open Packages/Installed Packages/syntax/Git Commit Message.tmLanguage`

If I change the syntax from "Git Commit Message" to "Git Commit View", then it just changes back the next time I run a commit.

How can I fix this so that syntax highlighting works in the commit message again?

Also, a bigger issue is that I can't commit anything using this package anymore. Typing a commit message and saving/closing doesn't commit anymore like it used to. 

I've been using this package for years and it's unfortunate that it has stopped working. Very frustrating as I depend on this package all the time.

Error message when closing the COMMIT_EDITMSG file:

```
Traceback (most recent call last):
  File "/Applications/Development/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 232, in on_close
    callback.on_close(v)
  File "git.commit in /Users/gary/Library/Application Support/Sublime Text 3/Installed Packages/Git.sublime-package", line 162, in on_close
  File "git.commit in /Users/gary/Library/Application Support/Sublime Text 3/Installed Packages/Git.sublime-package", line 132, in message_done
NameError: global name 'codecs' is not defined
```

I'm using Python 2.7.11 on a Mac. I've already tried uninstalling and re-installing the package.

How can I install an older version of the package for the time being?

**Comment by GaryKing** [comment]
Okay so I see the fix [is here](https://github.com/kemayo/sublime-text-git/commit/f59bc1f563dee560f36579980af7fd9e34243a72). When will this get pushed to Package Control? It seems like a pretty critical fix.

**Comment by slifin** [comment]
me and a co-worker have this issue as of this morning

**Comment by slifin** [comment]
how do you get access to the python files if you have downloaded the plugin via package control?

**Comment by Orlmente** [comment]
Same issue here, no color schemes for commits, and, more important, commits fails without notices, this since package updates to v1.0.1.
Win 7 64bit - sublime 3 latest dev.

**Comment by callebstrom** [comment]
You can manually open the Git.sublime-package file using 7-zip.

1. Close down sublilme text 3
2. Open the %APPDATA%\Installed Packages\Git.sublime-package file using 7-zip.
3. Navigate to git/commit.py and add "import codecs" directly after "import functools" and just add a new line before and after the added line.
4. Return to 7-zip and press update 

You will still receive the syntax error, however the commit and push functionality will now work.

**Comment by Orlmente** [comment]
@callebstrom,
yep ok, we can fix it by ourself, but the point is that this version render the whole package useless, so we hope for a quick fix (at least for the missing codecs import).

**Comment by kemayo** [comment]
I've popped out a new version with the codecs fix. I'll look into the syntax highlighting issue -- it doesn't happen (for me) if the package is installed as a regular directory, so it's more of a pain to debug.

**Comment by adavidof** [comment]
Same issue.

When I try: git commit

Error loading syntax file "Installed Packages/Git.sublime-package/syntax/Git Commit Message.tmLanguage": Unable to open Installed Packages/Git.sublime-package/syntax/Git Commit Message.tmLanguage

SublimeText 3 (Build 3083)

**Comment by kemayo** [comment]
I feel there's decent odds that ddd3591fda682ecb7bdfca5218fd5a031ba1e6ac will have improved matters.

**Comment by kemayo** [comment]
Okay, I actually jumped through the hoops and tested with zipped packages like some sort of goddamn savage. It works, and I'll take a new release.

**Comment by jonathanholvey** [comment]
Yes, that seems to have fixed it. Thanks a lot!
