### ISSUE TITLE
Plugin does not work at all - subprocess.Popen throws an exception

### ISSUE THREAD

**Issue by pfirsich** [kemayo/sublime-text-git#456]
I can not use the plugin at all and after pretty much everything I do in Sublime I get the following error in the console:

> Traceback (most recent call last):
>   File ".\threading.py", line 532, in __bootstrap_inner
>   File ".\git\__init__.py", line 204, in run
>   File ".\subprocess.py", line 633, in __init__
>   File ".\subprocess.py", line 842, in _execute_child
> TypeError: environment can only contain strings

I presume it has to do with this?:
http://stackoverflow.com/questions/12253014/why-does-popen-fail-on-windows-if-the-env-parameter-contains-a-unicode-object

I don't know what I'm doing wrong though, since no one else seems to have this problem.

**Comment by kemayo** [comment]
You using ST2 or ST3? Also, if you want to be particularly helpful, a copy of your environment would be handy. (You can get one by opening up the sublime console and typing in `import os; os.environ`.)

**Comment by pfirsich** [comment]
Im using ST2 (current version 2.0.2) and this is my environment: http://pastebin.com/w7DhskHZ
I really hope there is nothing I shouldn't have posted publicly. If you notice something, feel free to remove it as soon as you read it.

**Comment by jonathanolson** [comment]
I'm having the same problem, on ST2 (2.0.1 build 2217). Environment at https://gist.githubusercontent.com/jonathanolson/658aa7c3e2a2d8d1013f/raw/34dc434a9e2df451ef2090d8b10c5057adabc8bd/gistfile1.txt.

Exact same error message.

**Comment by gclyne1989** [comment]
I have the same problem as well with Windows 7 Sublime Text 2 and Python 2.7.11.

The work around is to comment out line 1 in sublime-text-git/git/__init__.py
from __future__ import absolute_import, unicode_literals, print_function, division

I got this idea from https://github.com/nvie/pip-tools/issues/209
