### ISSUE TITLE
commands.py overwrites built-in library

### ISSUE THREAD

**Issue by aclewis182** [kemayo/sublime-text-git#458]
When using this plug-in in conjunction with **Sublime-HTMLPrettify** causes HTMLPrettify to [fail](https://github.com/victorporof/Sublime-HTMLPrettify/issues/276).  The root cause is `commands.py` is overwriting the built in commands library (used for system commands).

I would suggest to rename command.py to something that doesn't shadow a system library.

**Comment by kemayo** [comment]
Oh, Sublime Text 2 and your not putting package-contents into their own module...

**Comment by aclewis182** [comment]
Yes I'm using ST2.  Which package-content?  For HTMLPrettify or do you mean for sublime-text-git?

**Comment by skywinder** [comment]
Related with https://github.com/victorporof/Sublime-HTMLPrettify/issues/107 and https://github.com/victorporof/Sublime-HTMLPrettify/issues/276

Please check @aclewis182 comments there.

**Comment by aclewis182** [comment]
@kemayo what did you mean by your previous comment?  Are you saying the HTMLPrettify is in the wrong with how it's packaging something? I'm not a dev on there but would like to know as I like both packages.

**Comment by aclewis182** [comment]
Ok so I saw your other comment.  To help others that find them self here; it won't be fixed in ST2.

**Comment by kemayo** [comment]
Well, it's fixed in ST2, insofar as I renamed the file. It's just that ST2 is *susceptible* to this issue in the first place, whereas ST3 isn't.
