### ISSUE TITLE
Not Correct Committer Info

### ISSUE THREAD

**Issue by lemke-ethan** [kemayo/sublime-text-git#459]
I have configured the package settings and git config settings and I am still not able to commit from Sublime Text 3 as myself. Every time I commit, it pulls info from my username (Windows username) and hostname. I have followed the suggestions and everything is configured properly, but it still does not work.

[master e394556] test
Committer: WindowsUsername <WindowsUsername@example.com>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 1 deletion(-)

**Comment by kemayo** [comment]
It's a configuration issue somewhere on your end. The git package just calls your system git install, so if it's saying your config isn't there then it's probably right.

Try opening a command prompt and using the commands it gives you -- it'll probably fix it for you.

**Comment by lemke-ethan** [comment]
The global was configured, so I configured the local as well and it appears to have fix the issue. 

Thanks for your help!

**Comment by lemke-ethan** [comment]
I already tried to edit the global config file via the first command and
all the settings are correct.

On Jan 26, 2016 5:37 PM, "David Lynch" <notifications@github.com> wrote:
>
> It's a configuration issue somewhere on your end. The git package just
calls your system git install, so if it's saying your config isn't there
then it's probably right.
>
> Try opening a command prompt and using the commands it gives you -- it'll
probably fix it for you.

**Comment by lemke-ethan** [comment]
Here are the logo image I have.
-- 
Thank you,
Ethan Lemke
