### ISSUE TITLE
Commands in refactored Git do not work at all in Sublime Text 2

### ISSUE THREAD

**Issue by astiob** [kemayo/sublime-text-git#463]
Every single command (and even just switching tabs) prints this to the console and appears to do nothing:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./git/statusbar.py", line 22, in run
  File "./git/__init__.py", line 258, in run_command
TypeError: __init__() keywords must be strings
```

This seems to be because `git/__init__.py` imports `unicode_literals` and then proceeds to do `kwargs['blah'] = blah; CommandThread(blah, **kwargs)` using string literals, which are now Unicode literals.

I’m still using ST2 because I’m still using Mac OS X 10.6. I could elaborate further, but that’s beyond the point. :)

**Comment by kemayo** [comment]
Hm, I don't see this when using ST2 myself, so I suspect it's something specific to the older version of OS X.

**Comment by kemayo** [comment]
I've speculatively added b007580 to see if it'll help. Shouldn't hurt, anyway.

**Comment by astiob** [comment]
That does seem to have done the trick, thanks. The values (as opposed to the keys) probably don’t need to be cast to str though, do they? Upon checking, it seems Python 2.7 allows Unicode keys in kwargs but 2.6 doesn’t; maybe that’s it.
