### ISSUE TITLE
Error in status bar for files not in a git repository

### ISSUE THREAD

**Issue by jcranendonk** [kemayo/sublime-text-git#466]
When opening a file in Sublime that is not in a git repository, the status bar contains the following text:

`git branch: fatal: Not a git repository (or any parent up to mount point <file path>) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).`

followed by the regular git status indicators.

This is using git v2.6.2 and sublime-text-git v1.0.5.

My current user settings for sublime-text-git are:

```json
{
    "status_opens_file": true,
    "git_command": "/usr/local/bin/git"
}
```

**Comment by kemayo** [comment]
The filesystem boundary stuff is interesting -- I presume that if we kept on going above this, there might actually be a directory which is part of a git repo?

**Comment by jcranendonk** [comment]
Possibly, but my specific situation there was not.

**Comment by jcranendonk** [comment]
Damn, you're fast. Thanks for the fix.
