### ISSUE TITLE
git commit prompts to save file, does not create commit

### ISSUE THREAD

**Issue by dylankb** [kemayo/sublime-text-git#472]
In ST2 git quick commit, add, status all work fine, however git commit is not working for me. 

After staging files and using git commit in Sublime, the commit message with the diff (COMMIT_EDITMSG) comes up. However when I save the file it saves to the default directory rather than the `.git` directory.

**Comment by dylankb** [comment]
Ahh, I should have read the instructions more carefully.

https://github.com/kemayo/sublime-text-git/wiki#commit

**Comment by kemayo** [comment]
Honestly, this is something I've been meaning to handle more elegantly for years now. I keep getting hit by that trying-to-save thing myself, and I _wrote_ this.
