### ISSUE TITLE
GitUpdateIgnoreCommand should consider all .gitignore files in project

### ISSUE THREAD

**Issue by esad** [kemayo/sublime-text-git#476]
Currently, only the `.gitignore` file in the project root is considered. Very often subdirectories/submodules have their own `.gitignore` files that are not taken into account.

**Comment by esad** [comment]
Perhaps a trick used by the sublime-gitignorer could be used instead of manually processing .gitignore files?

https://github.com/ExplodingCabbage/sublime-gitignorer/blob/master/gitignore_plugin.py#L171

**Comment by kemayo** [comment]
fa0c73aa35240ddc956e1b3d19ce1a3e913052aa does this, for it is a good idea.
