### ISSUE TITLE
Untracked files removed from sidebar (ST 3114)

### ISSUE THREAD

**Issue by goodguyry** [kemayo/sublime-text-git#477]
Since I updated to Sublime Text Build 3114 ([changelog](https://www.sublimetext.com/3)) I've noticed an issue where untracked files (those in `.gitignore`) are not remaining in the sidebar after a file is opened.

Once I initially open the project's containing folder, everything is fine. As soon as I click on a file/folder in the sidebar, the sidebar updates and all untracked files/folders are removed.

I see the following in the console:

```
Git: updating project exclusions ...
```

The command lists all files/folders contained in my global and local `.gitignore` files

Is there any way to block this behavior? I didn't see anything in `Git.sublime-settings`.

The only way I was able to fix the behavior ("fix" meaning "set it back to the way it was last week") was to remove your plugin.

Thanks. Let me know if you need additional information.

**Comment by kemayo** [comment]
It can be disabled by setting `gitignore_sync` to `false` in the package settings.

**Comment by goodguyry** [comment]
That did it. Thanks a lot!

**Comment by kemayo** [comment]
I should really check whether project files will respect the binary_file_patterns preference, and set that as an option. It'd keep them in the sidebar, but exclude them from search. (Good ol' `node_modules`, bane of search / the file picker.)

**Comment by kemayo** [comment]
The bad news, incidentally, is that you can't per-project override binary_file_patterns, so this approach is about as good as we'll get for now.

**Comment by goodguyry** [comment]
Thanks for looking into an alternative.

**Comment by nikoladev** [comment]
Is this on the list of features to be implemented? I would really love to keep my ignored files in the sidebar without them constantly being re-indexed.

**Comment by kemayo** [comment]
It's on the list of things I'd like to have, but which remain poorly-supported by Sublime.

**Comment by nikoladev** [comment]
I guess I'll have to with it for now :) Thanks for the reply!
