### ISSUE TITLE
.gitignore behavior was unexpected

### ISSUE THREAD

**Issue by ScottyMJacobson** [kemayo/sublime-text-git#478]
So it looks like some of the most recent commits, including fa0c73aa, implemented .gitignore tracking to add all these files to excluded patterns. As far as I remember, up until the update, this wasn't the expected behavior of the plugin, and .gitignored files and folders were not excluded by default and still appeared on the sidebar. Should this behavior be enabled by default?

(edit: when I wrote my first post I thought I had set the setting to false and was still seeing the excluding. looks like this is indeed what the setting `gitignore_sync` does)

Thanks!

**Comment by mvmohitverma54** [comment]
octocat created a gitignore file which is much more stable than this try to replace that mine works

**Comment by jkoelling** [comment]
I also stumbled over this. The `gitignore_sync` would benefit from a better explanation in the settings file.

**Comment by kemayo** [comment]
9f287b1 improves the comment, as that's a good idea.

An overall-better behavior would rely on Sublime implementing better sidebar APIs, unfortunately. (I'd like it to happen someday -- highlighting changed files would also be nice.)
