### ISSUE TITLE
Display colors to Folders sidebar reflecting Git status

### ISSUE THREAD

**Issue by xwartz** [kemayo/sublime-text-git#481]
Like Atom

![image](https://cloud.githubusercontent.com/assets/4149827/16707425/3bb833ba-45ff-11e6-94a5-4b4265f40279.png)

**Comment by josegonzalez** [comment]
Duplicate of https://github.com/kemayo/sublime-text-git/issues/204, so this should be closed.

**Comment by kemayo** [comment]
Indeed. As said in #204, the APIs for this aren't there.
