### ISSUE TITLE
Support view commits by Hash ID on log graph window

### ISSUE THREAD

**Issue by watergear** [kemayo/sublime-text-git#492]

**Comment by kemayo** [comment]
Sensible request, one second, I'll have to lightly rewrite the Graph syntax to make it fit together.

**Comment by watergear** [comment]
@kemayo I have implemented it few days ago and will make pull request later.
Could you reopen this issue?

**Comment by kemayo** [comment]
Do I need to? I mean, I already implemented what I think you're asking for...?

**Comment by watergear** [comment]
Do you mean the commit cf56cde327a552c46811fcd98af22aa8c39231bf ?
I suppose to Press a key to show commit when current cursor stay on Hash ID.

Just leave this issue for few days. I will update the details on description.
thanks

**Comment by kemayo** [comment]
No, I mean 47a3228 -- the one that I closed the task with. It extends the existing "hit enter to go to commit in blame" behavior to also work in graph.

**Comment by watergear** [comment]
But I hit enter key and then nothing happens?
What is wrong?

**Comment by kemayo** [comment]
Hard to say. Assuming there are no errors in the log, it's either that you're pressing enter on a line which doesn't contain a commit hash, or you've not updated to the version which includes the new functionality (I haven't tagged a release since making that change, for one thing).

**Comment by watergear** [comment]
Anyway, I will make pull request later and you will see the details.

**Comment by kemayo** [comment]
Sure, I will be happy to examine it.
