### ISSUE TITLE
Why wiki is not updated?

### ISSUE THREAD

**Issue by barbossa** [kemayo/sublime-text-git#499]
We have [wiki](https://github.com/kemayo/sublime-text-git/wiki), but last update was 1 year ago. Is during this time nothing has changed? Even the title of the page relates for Sublime Text **2**, about the version 3 is no mention :(
![screenshot_304](https://cloud.githubusercontent.com/assets/1926453/19128423/eee8c742-8b4b-11e6-9dc0-4adf9462f56f.png)

**Comment by Gabriel-p** [comment]
I'd very much like to see a Wiki update. Perhaps that'll help me resolve issue #498.

**Comment by kemayo** [comment]
I updated it a little bit so it's slightly less "ST2" focused.
