### ISSUE TITLE
Help with keybindings?

### ISSUE THREAD

**Issue by asscore** [kemayo/sublime-text-git#509]
Hello,

I am trying to bind some git commands to some key combinations in my user keymap file.

Here is what I have in my keymap:
`[
	  { "keys": ["`"], "command": "reindent"},
	  { "keys": ["ctrl+plus"], "command": "git add"},
	  { "keys": ["ctrl+minus"], "command": "git commit"},
	  { "keys": ["ctrl+home"], "command": "git push"},
]`

I enabled logging in console, and when I test out my bindings I get:

`Unable to parse command: git add
command: git commit
Unable to parse command: git commit
command: git push
Unable to parse command: git push
`

Any ideas on what I am doing wrong?

Thanks for the help.

**Comment by kemayo** [comment]
Take a look at the [Default.sublime-commands](https://github.com/kemayo/sublime-text-git/blob/master/Default.sublime-commands) in the plugin for the right command names to use. E.g. `git add` should probably be `git_add_choice` instead, etc.
