### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by mittalyashu** [kemayo/sublime-text-git#528]
I have installed the git on the sublime, but don't know, how to start using it.

**Comment by strongdoctor** [comment]
Ctrl-Shift-P -> Git: Pull or whatever you wish to do.

**Comment by mittalyashu** [comment]
Thanks. Can you add this in the `readme.markdown` file too. By Creating a `usage section`.

**Comment by mittalyashu** [comment]
It's still quite difficult to understood how to use it and what are the commands.
Is there is any kind of help video?

**Comment by kemayo** [comment]
"What are the commands?" is mostly answered as "they're the normal git commands". This is a fairly thin layer over command-line git, so you're probably going to get the best results by just following a regular (git tutorial)[https://try.github.io/].

Alternately, you can get a pretty comprehensive command list by just opening the command palette (cmd-shift-p) and then typing in "git", which will filter it down to just the commands to do with git.

**Comment by mittalyashu** [comment]
I know that git commands. But don't know, how to use it on the sublime text git interface?
