### ISSUE TITLE
Request: Add Publish Branch

### ISSUE THREAD

**Issue by astronouth7303** [kemayo/sublime-text-git#533]
Basically, dropping down to a terminal to do a `git push -u origin <cur branch>` is kinda really annoying. Git: Push Current Branch kinda does it, but I have to do it for everything and doesn't set it for any other tools.

I would like to request a command be added to basically do this, bonus points for doing the right thing if the default remote isn't `origin` or if there's more than one remote.

**Comment by kemayo** [comment]
Already exists, as the `Git: Track Remote Branch` command.

**Comment by kemayo** [comment]
Actually... I misread you a little, and that's not *quite* what you wanted. One second.
