### ISSUE TITLE
What is git push tags?

### ISSUE THREAD

**Issue by mittalyashu** [kemayo/sublime-text-git#534]
What is git push tags?

![image](https://user-images.githubusercontent.com/29014463/31246985-ccbe37aa-aa2c-11e7-8424-ed68e0271d5b.png)

I know about `git tag`, but not sure about `git push tags`.

**Comment by geniusupgrader** [comment]
read the section "Sharing Tags" on [this site](https://git-scm.com/book/en/v2/Git-Basics-Tagging).
