### ISSUE TITLE
Sidebar to show modified files since last commit

### ISSUE THREAD

**Issue by elfassy** [kemayo/sublime-text-git#54]
Similar to what Aptana Studio 3 does, it would be nice to show in the sidebar the files that were modified (maybe add a \* next to them).

Thanks!

**Comment by nicejwjin** [comment]
+1

**Comment by marspe** [comment]
+1

**Comment by clampist** [comment]
+1

**Comment by SreedevSB** [comment]
+1

**Comment by cmalard** [comment]
@kemayo : looks like this is possible on ST3 with file icon :-)

Not sure there is a way to do it in the "open files" zone, but that's still a start :+1:
