### ISSUE TITLE
Disable git comments

### ISSUE THREAD

**Issue by iamarmanjon** [kemayo/sublime-text-git#560]
Hi there,

How do I disable this? I tried toggling the annotation setting but I don't think that is. Check the package settings but not sure what settings to switch. This happen when I click on a line.

![screen_shot_2018-09-13_at_12_00_36_pm](https://user-images.githubusercontent.com/7567758/45466569-2a9b8480-b74d-11e8-92d6-0bb19c339f9e.png)

**Comment by lipanski** [comment]
@iamarmanjon that's actually a [GitGutter](https://github.com/jisaacks/GitGutter) feature. had the same issue and managed to disable it by setting `"show_line_annotation": false` in the GitGutter configuration file.

**Comment by iamarmanjon** [comment]
:D sorry, I should have debug more. Closing this.
