### ISSUE TITLE
Git not installed?

### ISSUE THREAD

**Issue by lucasRolff** [kemayo/sublime-text-git#96]
Hi,

I have git installed on my Mac, and I wanted to install the git plugin using Package Control in ST2, when I do, it gets installed, I restart sublime, but when I then try running the git: in the cmd + shift + P it doesn't show any git: commands at all?

Best regards,
Lucas Rolff

**Comment by dannyid** [comment]
So much love for @chrismadrigal's solution. Worked like a charm.

**Comment by chrismadrigal** [comment]
👍
