### ISSUE TITLE
Push not working

### ISSUE THREAD

**Issue by phisch** [kemayo/sublime-text-git#98]
Hi there,

if i try to push something on github, the command git push doesnt do anything at all. I dont even get a message in the console.
I am new to git and github, when i push something with the git-bash it asks me for my passphrase (is this normal), could this has something to do with the not working push command in the sublime git plugin?

I hope there is a solution for this problem, it would be so nice to controll all of this with SublimeText2!

Kindly regards
Philipp Schaffrath

**Comment by melior88** [comment]
The solution posted by @davidhurley works fine on my case! Thanks a lot!

**Comment by learawesome** [comment]
I don't have a windows machine, But I've got the same problem on my Mac.

when I do a git push on Mac terminal through  git@github.com...... things works fine.
but when I do the push in the sublime text it just doesn't work, and throughout this "error":

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I try the same repo both on my Mac and Linux machine, the Linux sublime text git push works fine.

I've also tried the solution given by @PhilippSchaffrath, problem still not solved.

the answer proved by @cellulosa give me a thought, I just installed the [github client](https://desktop.github.com), sign in, then came back to the sublime text  do a git push everything works!

Don't know why it works, but anyone confront with similar issue on Mac as me you can have a try.

**Comment by PhilippSchaffrath** [comment]
I think it might be possible that this plugin was trying to access your private repository through https instead of ssh authentication, which would lead github to ask for authentication. This is most likely be caused by you have not setting up your ssh-key properly.

Probably the github client was correctly setting up your ssh keys, thats why you could solve the problem.

**Comment by martriay** [comment]
@learawesome I tried your solution but it didn't work.

First I try to push:
![image](https://cloud.githubusercontent.com/assets/1703831/19439708/864d604a-9455-11e6-8a01-1ca6c65298ff.png)

Then it asks for an upstream:
![image](https://cloud.githubusercontent.com/assets/1703831/19439714/8b0050d4-9455-11e6-9fb6-a7545c92c777.png)

Then I select `origin`:
![image](https://cloud.githubusercontent.com/assets/1703831/19439723/900318b4-9455-11e6-9633-44a00b7b133f.png)

After this step it does nothing, not even logging into the console.
I have no clue what could be happening.
